### ISSUE TITLE
Disk Usage 100%

### ISSUE THREAD

**Issue by alionti998** [Microsoft/winfile#39] opened 2018-04-10 00:13 UTC
Disk usage for File Manager winfile.exe goes to 100% shortly after launching the application.

![image](https://user-images.githubusercontent.com/22989161/38529331-3552c442-3c32-11e8-8a6e-d2b8810bb570.png)

![image](https://user-images.githubusercontent.com/22989161/38529344-4ba2690a-3c32-11e8-91e0-955febdc19f1.png)

**Comment by craigwi** [comment] 2018-04-10 00:16
That is caused by the goto index (of C: only) getting created.  I suppose there might be some way to throttle it.

**Comment by NazmusLabs** [comment] 2018-04-10 12:54
Yeah, for now, I'd just keep this app open in the background when you are not using this PC until indexing is done. That way, you'll have a fast search experience and it won't spike up disk usage the next time you launch the app because the initial indexing has already been done.

**Comment by roytam1** [comment] 2018-04-10 13:33
maybe we can just disable it?
https://github.com/Microsoft/winfile/blob/master/src/wfinit.c#L1452

**Comment by T8z5h3** [comment] 2018-04-10 14:26
yes, i was jest saying that the built in indexing could fix the 100% disk usage issue at least on the branch where we are updating the code.

**Comment by craigwi** [comment] 2018-04-10 16:43
I would be ok with adding an option to the Options menu to turn off the indexing.

**Comment by T8z5h3** [comment] 2018-04-10 16:57
i say go for it... the search option seems like it does not need to index.

**Comment by matthewjustice** [comment] 2018-04-13 12:31
In my testing, I see that **CPU** is maxed out (for a single thread) at startup, but not **disk** usage. The CPU time I see is in wfgoto.cpp BuildDirectoryTreeBagOValues.  

@craigwi - Is BuildDirectoryTreeBagOValues the code you meant by: 

> the goto index (of C: only) getting created. 

I'm wondering if there are two issues here, or is the disk issue also related to this code? I'm unable to reproduce high disk usage.

**Comment by roytam1** [comment] 2018-04-13 14:33
@matthewjustice high disk usage happens here. Tried logging with filemon and winfile keeps looking up in same folder(which has several thousands files in total of ~3.3GB in size)

**Comment by matthewjustice** [comment] 2018-04-13 14:44
@roytam1 Interesting, good to know. I can't reproduce that, but it is probably a difference in my system and what I have on the c: drive.

I just submitted PR #91 to add a menu option to disable the indexing at startup.

**Comment by craigwi** [comment] 2018-04-16 21:14
I merged PR #91.  If there is some other problem, open a new issue with specifics.

**Closed by craigwi** 2018-04-16 21:14 UTC
Labels: help wanted
