### ISSUE TITLE
chocolatey installation

### ISSUE THREAD

**Issue by iamkarlson** [Microsoft/winfile#7] opened 2018-04-09 08:55 UTC
Are there any ideas about installation from chocolatey or Install-Package?

**Comment by mircsicz** [comment] 2018-04-09 11:13
+1

**Comment by craigwi** [comment] 2018-04-09 11:30
I'm open to one or both of those means of distribution.  Can you propose some simple changes?

**Comment by iamkarlson** [comment] 2018-04-09 11:45
@craigwi I could probably send you a PR later. If you feel that you're able to follow that [manual](https://blog.gripdev.xyz/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/) it would be really nice. My main concern was that I couldn't download a ready-to-use executable file. So I created [appveyor](https://ci.appveyor.com/project/iamkarlson/winfile/build/artifacts )as a temp solution

**Comment by craigwi** [comment] 2018-04-09 16:05
As for a pre-built binary, you can find one at https://github.com/Microsoft/winfile/releases/tag/v10.0.  

I'll take a look at the manual and look for your PR later.

**Comment by craigwi** [comment] 2018-04-17 20:32
Question: if we go the Windows Store route, do we need chocolatey or other package/distribution format?

**Comment by NazmusLabs** [comment] 2018-04-17 20:57
@craigwi yes, of course, for Window 7 and 8 users as well as Windows 10 LTSB releases prior to Anniversary update, all of which don't support the technology required for the store version.

This also is needed for Windows Server releases that don't include the Windows Store.

**Comment by craigwi** [comment] 2018-04-24 00:45
I setup a simple CI process using visualstudio.com which puts the builds of master at https://winfilerelease.blob.core.windows.net/craigwi/Winfile.exe (and pdb too).  Can you verify you can access that location?

Updating the version # not yet done.

**Comment by NazmusLabs** [comment] 2018-04-24 00:58
@craigwi yes, I can access the location. It immediately prompts to save the exe file without asking for any type of authentication.

However, Windows SmartScreen attempts to block the application from running. It also has an "unknown" publisher. I suppose this calls for a separate issue related to signing and smartscreen?

**Comment by craigwi** [comment] 2018-04-24 01:24
The lack of authentication is intentional.  My next step is to get the bits signed by a Microsoft key to avoid the SmartScreen issue.

**Comment by NazmusLabs** [comment] 2018-04-24 01:50
@craigwi right, exactly! Sorry, if my wording made it sound like it was an issue. I understood that you wanted to ensure people from outside Microsoft would be able to access it, and I verified that it would, as intended. :) The smartscreen bit was what I intended to point out as an issue.

**Comment by NazmusLabs** [comment] 2018-04-24 02:00
One quick point I forgot to note about Windows Server 2016 and 2019. Server 2016 and 2019 can run the Windows Store package, but it needs to be installed through either PowerShell or App Installer (if the user has that component installed on their server installation). However, since Server 2016 and 2019 doesn't have the Store services installed (not even as an optional role), it can't auto update and need to be manually updated by the user using an updated Appx package.

So, in summery, I can outline it as follows.

### Windows OS versions that support the Store package

- Windows 10 Version 1607 or higher (Both install & auto updating from the Store and manual install & update are supported)
- Windows 10 LTSB/LTSC Version 1607 or higher (manual install & update only)
- Windows Server 2016 (manual install & update only)
- Windows Server 2019 (manual install & update only)

**Comment by thecatkitty** [comment] 2018-04-24 19:06
@craigwi Yeah, releasing the retro branch for choco or WS would make a little sense, I think. I also doubt that visualstudio.com could provide us with a build system targeting W9x, NT or 16-bit.

But maybe there is a way to have some sort of semi-automatic builds and releases of retro? Or there is just no will to do that?

**Comment by NazmusLabs** [comment] 2018-04-24 20:12
Sounds like a good way to approach this for now. I'm guessing things will evolve with time as we learn what works and doesn't work. So, this is a great starting point.

As for the retro branch, I also agree. Those can be standalone releases in the future. But even standalone releases are far in the future. I believe the retro branch as a lot of work to be done before it's near satisfactory level to have a release. So, I'm going to think about how releases for that would go once we get to a point where the application successfully compiles and is stable on Windows NT, 2000, at very least.

**Comment by craigwi** [comment] 2018-04-30 14:30
Any feedback on the the above?  The alpha version is published so you can install it: choco install winfile -pre.

**Comment by craigwi** [comment] 2018-05-01 14:04
My submissions have been approved.  The following commands work:

choco install winfile --version 4.0
choco install winfile --version 10.0.0.0
choco install winfile -pre 

Once I get the signing stuff to work, I'll make this a more regular process.

**Comment by NazmusLabs** [comment] 2018-05-01 21:59
@craigwi so will the -pre parameter give you a build from the latest commit eventually, or is that not possible because new builds must be approved?

**Comment by craigwi** [comment] 2018-05-02 03:41
AFAIK, pre-release builds in chocolatey (with "-<name>" after the version) only require automated tool checks.  Which version 10.0.1804.0-alpha got in a few hours.  I don't think we can use that for every commit, but often.

I got signing approval from Microsoft and the CI builds will be signed, which should make use of them much easier.  To be tested...

**Comment by craigwi** [comment] 2018-05-04 22:40
Signed binaries are available now:

https://winfilerelease.blob.core.windows.net/craigwi/Win32/winfile.exe
https://winfilerelease.blob.core.windows.net/craigwi/x64/winfile.exe

pdb are there too.  Paths are case sensitive; sorry...

I will publish a build per commit at those paths going forward.

**Comment by craigwi** [comment] 2018-05-04 22:46
Oops.  The pdb files are ..../Winfile.pdb (capital 'W').

**Comment by ad43** [comment] 2018-05-05 10:07
Like pouring smooth oil... A dream on my Win10 Pro v1709 originally built in Aug 2011 and upgraded ever since, including old Winfile.exe v4.0.1381.318 which only stopped being able to see OneDrive on Win10 earlier this year. Many thanks for all this work.

**Comment by NazmusLabs** [comment] 2018-05-05 20:14
@ad43 How did you get this specific version number? v4.0.1381.318

**Comment by peterooch** [comment] 2018-05-05 20:17
@NazmusLabs https://en.wikipedia.org/wiki/Windows_NT_4.0

**Comment by ad43** [comment] 2018-05-05 22:10
Yes, it's a winfile.exe that has been in daily use on my Win10 PC. Version reported by explorer.

![winfileproperties](https://user-images.githubusercontent.com/38399939/39667951-f7f4747c-50b0-11e8-987b-b3b3619b794d.jpg)

**Comment by thecatkitty** [comment] 2018-05-08 21:58
@craigwi why is SmartScreen still whining about an executable with Microsoft CA in its certificate chain?

![2018-05-08 3](https://user-images.githubusercontent.com/35971468/39785122-38e89a3c-531b-11e8-9b71-4b405f3199a0.png)

The second minor issue with the signed executable is that the displayed name is weird when You run it with Administrator rights (I personally do not think that _Sign Winfile x64_ is a very appealing name):

![2018-05-08 4](https://user-images.githubusercontent.com/35971468/39785181-7b68ed58-531b-11e8-9401-1d3af69fc012.png)

**Comment by craigwi** [comment] 2018-05-09 18:49
Hi @thecatkitty.  I reached out to the SmartScreen team about the first point.  Thanks for the note about the second part; I should be able to fix that.

**Comment by craigwi** [comment] 2018-05-11 23:43
Here is the answer I got from the SmartScreen team:

"The reason for the warning was that the signing certificate didn’t yet have reputation in our system. There are a number of factors that contribute to gaining reputation, such as download traffic, download history, past anti-virus results and URL reputation. Only Extended Validation Authenticode certificates are able to provide immediate reputation. Microsoft certificates are handled the same way as other certificates. Once they have established reputation, any applications signed with the same certificate will have a warn-free experience. 

The certificate your application is signed with has gained reputation, so warnings should not be displayed any longer."

If you still see the SmartScreen warning, let me know.

**Comment by clzls** [comment] 2018-05-15 08:10
The SmartScreen still warns it to be from a Unknown Publisher.

If it's a person outside Windows running this project, he may not get this problem solved as quickly. LOL

**Comment by craigwi** [comment] 2018-05-15 13:55
Are you using one of the following links: 

https://winfilerelease.blob.core.windows.net/craigwi/Win32/Winfile.exe
https://winfilerelease.blob.core.windows.net/craigwi/x64/Winfile.exe

Those are the only signed versions right now.  I haven't updated the chocolatey package yet.

**Comment by clzls** [comment] 2018-05-15 14:01
@craigwi Yes. (at a very slow speed of ~0.5 KB/s in China. ) Windows Defense marks it as _unrecognizable_.

![image](https://user-images.githubusercontent.com/16474386/40061379-5de1b010-588b-11e8-8071-9cbc55628394.png)

**Comment by craigwi** [comment] 2018-05-15 22:10
BTW, the string "Sign Winfile x64" referenced by @thecatkitty above came from the SignConfig.xml file that I added to guide the signing process.  I changes this to "Winfile x64" and have asked the internal team if I can have more control over that.

**Comment by craigwi** [comment] 2018-05-16 21:06
Chocolatey approved the 1805.1 release.  I am closing this since the issue is solved.  The Windows Store release is recorded in #85.

**Closed by craigwi** 2018-05-16 21:06 UTC
