### ISSUE TITLE
No Toolbar-Buttons since (49597b8c423b8e8d16ee252adc1e6e8f69e8c1ac)

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#111] opened 2018-04-18 06:20 UTC
Hi,

the toolbar **buttons** are gone with the checkin (49597b8c423b8e8d16ee252adc1e6e8f69e8c1ac) 

Squashed commit of the following: 
16. April 2018 10:44:13

Only the pictures are left. Is this a Win7 only behavior or a preparation for visual styles?

The following lines are addes in winfile.c

`#pragma comment(linker, "\"/manifestdependency: \`
`    type = 'Win32'                              \`
`    name = 'Microsoft.Windows.Common-Controls'  \`
`    version = '6.0.0.0'                         \`
`    processorArchitecture = '*'                 \`
`    publicKeyToken = '6595b64144ccf1df'         \`
`    language = '*'                              \"")`

Greetings
Daniel

**Comment by thecatkitty** [comment] 2018-04-18 06:28
It is not a bug. Moreover, it is an **intended part** of using the visual styles.

**Comment by BaldwinTechnology** [comment] 2018-04-18 06:51
I have supposed something.
But how can I get the old style back?

**Comment by thecatkitty** [comment] 2018-04-18 06:57
I am not sure, but perhaps setting __Disable visual themes__ in winfile.exe compatibility properties will help?

**Comment by ZanderBrown** [comment] 2018-04-18 09:06
@thecatkitty that may help but I seem to remember that disables Aero as well?

Having this as an option should probably be investigated

**Comment by thecatkitty** [comment] 2018-04-18 09:25
@ZanderBrown Windows _of course_ [enables us to do that](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175(v=vs.85).aspx#turnoff). We might add such option to the menu (it starts to seem like the _Preferences_ dialog could become a good thing to add) but it would create a dependency on `uxtheme.dll`... Shall we use LoadLibrary then?

**Comment by Biswa96** [comment] 2018-04-18 09:27
First check if that API works for WinXP or Vista.

**Comment by ZanderBrown** [comment] 2018-04-18 12:43
Yes LoadLibrary would seem the way to go, I think for now the Options menu is fine but maybe we should have a separate dialog for all the additions over the original WinFile features

**Comment by NazmusLabs** [comment] 2018-04-23 18:47
This issue has been now fixed in the latest commit. I think this can be closed.

**Closed** 2018-04-24 05:30 UTC
